//======================== REGISTER
export const REGISTER_USERNAME_CHANGED = 'REGISTER_USERNAME_CHANGED';
export const REGISTER_EMAIL_CHANGED =  'REGISTER_EMAIL_CHANGED';
export const REGISTER_PASSWORD_CHANGED = 'REGISTER_PASSWORD_CHANGED';
export const REGISTER_CONFIRMPASSWORD_CHANGED = 'REGISTER_CONFIRMPASSWORD_CHANGED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const ON_USER_REGISTER = 'ON_USER_REGISTER';

//======================== LOGIN
export const LOGIN_EMAIL_CHANGED = 'LOGIN_EMAIL_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const ON_USER_LOGIN = 'ON_USER_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//======================== LOGOUT 
export const LOGOUT_USER = 'LOGOUT_USER';