//======================== REGISTER
export const REGISTER_USERNAME_CHANGED = 'REGISTER_USERNAME_CHANGED';
export const REGISTER_EMAIL_CHANGED =  'REGISTER_EMAIL_CHANGED';
export const REGISTER_PASSWORD_CHANGED = 'REGISTER_PASSWORD_CHANGED';
export const REGISTER_CONFIRMPASSWORD_CHANGED = 'REGISTER_CONFIRMPASSWORD_CHANGED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const ON_USER_REGISTER = 'ON_USER_REGISTER';

//======================== LOGIN
export const LOGIN_EMAIL_CHANGED = 'LOGIN_EMAIL_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const ON_USER_LOGIN = 'ON_USER_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//======================== LOGOUT 
export const LOGOUT_USER = 'LOGOUT_USER';

//======================= CHECKOUT
export const CHECKOUT_FAILED = 'CHECKOUT_FAILED';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECK_DATA_CUSTOMER = 'CHECK_DATA_CUSTOMER';

//====================== DATA_CUSTOMER_ADD
export const ON_CUSTOMER_ADD_ADDRESS = 'ON_CUSTOMER_ADD_ADDRESS';
export const ADD_DATA_CUSTOMER_FAILED = 'ADD_DATA_CUSTOMER_FAILED';
export const ADD_DATA_CUSTOMER_SUCCESS = 'ADD_DATA_CUSTOMER_SUCCESS';  